### ISSUE TITLE
use state in async action

### ISSUE THREAD

**Issue by megadidar** [Dimillian/SwiftUIFlux#6]
Hello @Dimillian 

Can you please tell me why state parameter in execute function is always null in async actions?

`    func execute(state: FluxState?, dispatch: @escaping DispatchFunction) {
        // state is null
    }`

**Comment by Dimillian** [comment]
In the app I'm using my library, the state is not null. 
<img width="1033" alt="Screenshot 2019-11-06 at 14 48 29" src="https://user-images.githubusercontent.com/535509/68303646-92750300-00a4-11ea-93e5-f6cfedcf59d7.png">

Maybe it's a side effect of something else?

**Comment by megadidar** [comment]
@Dimillian 
Looks like it is AppState rather than Child State.
Working!
Thank you!

**Comment by ethanyuwang** [comment]
how do i access the child state? I tried to do something like:

state.userState

but just gets an error saying Value of type 'FluxState?' has no member 'userState'
